### ISSUE TITLE
Overriden SessionId

### ISSUE THREAD

**Issue by jrmitch120** [api-ai/api-ai-net#4]
Is it intentional that the [SessionId of the AIDataService is overwriting the SessionId passed in on an AIRequest](https://github.com/api-ai/api-ai-net/blob/6ce55ada19e18db0272634e26646a1eaa1f502a2/ApiAiSDK/AIDataService.cs#L58)?

I spent a large chunk of time trying to figure out why my sessions weren't propagating across requests.  This seems like somewhat confusing behavior to me.  Thanks!

**Comment by xVir** [comment]
Hi, @jrmitch120 
Sorry, I did not describe that it is not intended to change `SessionId` from client code. SessionId is generated automatically while an `AIDataService` creating. 
Do you have a special case and need to set up your special `SessionId`?
Thanks.

**Comment by jrmitch120** [comment]
I have a case where I have a number of required parameters defined for an intent on Api.Ai.  If all of these parameters are not captured in the original query, then I need to pass the same ```SessionId``` on subsequent queries to fill them out. 

Right now, all queries are treated as unique sessions unless you define a ```SessionId``` on the ```ApiAi```.```AIConfiguration``` and use it for running related queries.  This sets it on the ```AIDataService``` so that ```SessionId``` is not automatically generated.

Really the source of confusion is that the ```SessionId``` on the ```AIRequest``` is overridden without any indication that it's going to do so :).  I may be mistaken, but I don't think nuget version 1.6.1 of  ```AIResponse``` contains ```SessionId```, which made it tricky to figure out that it is being changed.

**Comment by xVir** [comment]
Hi, @jrmitch120 
Yes, there are two [ways](https://github.com/api-ai/api-ai-net/blob/master/ApiAiSDK/AIDataService.cs#L43)
If `sessionId` specified in `AIConfiguration` it will be used. Otherwise, it will be generated.

So, the `sessionId` value may be different if you use several `AIDataService` instances.

I have created [update](https://github.com/api-ai/api-ai-net/commit/a1b9b5c0e69fa36be4739f587f640e73c0e3fdeb) for the SDK. Now the `SessionId` in request is hidden.

Thanks.

**Comment by jrmitch120** [comment]
Thanks!  Less confusing now :)
